---

all:
  hosts:
    k3s-s-1:
      ansible_host: 172.16.10.31
    k3s-w-1:
      ansible_host: 172.16.10.32
    k3s-w-2:
      ansible_host: 172.16.10.33
    k3s-w-3:
      ansible_host: 172.16.10.34
    k3s-w-4:
      ansible_host: 172.16.10.36
  children:
    control_nodes:
      hosts:
        k3s-s-1:
    generic_nodes:
      hosts:
        k3s-w-1:
        k3s-w-2:
        k3s-w-3:
        k3s-w-4:
    longhorn_nodes:
      hosts:
        k3s-w-1:
        k3s-w-2:
        k3s-w-3:
        k3s-w-4:
