---
version: '3'

vars:
  PROJECT_DIR:
    sh: "git rev-parse --show-toplevel"
  CLUSTER_DIR: "{{.PROJECT_DIR}}/cluster"
  ANSIBLE_DIR: "{{.PROJECT_DIR}}/infra/ansible"

env:
  KUBECONFIG: "{{.PROJECT_DIR}}/kubeconfig"

includes:
  ansible: .taskfiles/ansible.yml
  secrets: .taskfiles/secrets.yml

tasks:
  default:
    cmds:
    - task -l
    silent: true